const regions = [
  {key:"forehead", name:"額", instruction:"眉の上から生え際までをROIにします。髪・眉・メガネをできるだけ外してください。", roi:{l:.18,t:.18,r:.82,b:.56}},
  {key:"rightCheek", name:"右頬", instruction:"目の下〜口角上、鼻横〜耳側の頬だけをROIにします。", roi:{l:.18,t:.18,r:.86,b:.80}},
  {key:"leftCheek", name:"左頬", instruction:"目の下〜口角上、鼻横〜耳側の頬だけをROIにします。", roi:{l:.18,t:.18,r:.86,b:.80}},
  {key:"nose", name:"鼻", instruction:"鼻筋〜小鼻をROIにします。目・口・頬をできるだけ外してください。", roi:{l:.28,t:.12,r:.72,b:.86}}
];
const state={current:0,sessionName:"",lightingPreset:"left-raking",regions:{}};
const $=id=>document.getElementById(id);
const wizard=$("wizard"),summaryTabs=$("summaryTabs"),roiCanvas=$("roiCanvas"),rctx=roiCanvas.getContext("2d"),analysisCanvas=$("analysisCanvas"),actx=analysisCanvas.getContext("2d",{willReadFrequently:true});
let frontURL=null,rakingURL=null,lastMetrics=null,roi=null,roiConfirmed=false,editorImage=null,imageRect=null,dragging=null;
const currentRegion=()=>regions[state.current];
const cloneROI=x=>({l:x.l,t:x.t,r:x.r,b:x.b});
function buildWizard(){wizard.innerHTML="";regions.forEach((r,i)=>{const b=document.createElement("button");b.type="button";b.className="step";if(i===state.current)b.classList.add("active");if(state.regions[r.key])b.classList.add("done");b.textContent=`${i+1}. ${r.name}`;b.onclick=()=>switchRegion(i);wizard.appendChild(b);});}
function switchRegion(i){state.current=i;frontURL=null;rakingURL=null,lastMetrics=null,editorImage=null,imageRect=null,dragging=null;const saved=state.regions[currentRegion().key];if(saved){frontURL=saved.frontDataUrl||null;rakingURL=saved.rakingDataUrl||null;roi=saved.roi?cloneROI(saved.roi):cloneROI(currentRegion().roi);roiConfirmed=!!saved.roiConfirmed;lastMetrics=saved.metrics||null;}else{roi=cloneROI(currentRegion().roi);roiConfirmed=false;}updateUI();}
function updateUI(){const r=currentRegion();$("regionHeading").textContent=`3. ${r.name} の画像`;$("progressText").textContent=`${state.current+1} / ${regions.length}`;$("regionInstruction").innerHTML=`<b>${r.name}</b>: ${r.instruction}`;["frontInput","rakingInput","frontCameraInput","rakingCameraInput"].forEach(id=>$(id).value="");$("frontPreview").removeAttribute("src");$("rakingPreview").removeAttribute("src");$("frontSourceStatus").textContent="未選択";$("rakingSourceStatus").textContent="未選択";if(frontURL){$("frontPreview").src=frontURL;$("frontSourceStatus").textContent="保存済み";}if(rakingURL){$("rakingPreview").src=rakingURL;$("rakingSourceStatus").textContent="保存済み";}fillMetrics(lastMetrics);setROIStatus();prepareEditor();clearAnalysis();buildWizard();renderSummary();}
function dataUrlFromFile(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file);});}
async function setImage(kind,file,label){if(!file)return;const url=await dataUrlFromFile(file);if(kind==="front"){frontURL=url;$("frontPreview").src=url;$("frontSourceStatus").textContent=label;roi=cloneROI(currentRegion().roi);roiConfirmed=false;await prepareEditor();}else{rakingURL=url;$("rakingPreview").src=url;$("rakingSourceStatus").textContent=label;if(!frontURL){roi=cloneROI(currentRegion().roi);roiConfirmed=false;await prepareEditor();}}lastMetrics=null;fillMetrics(null);clearAnalysis();setROIStatus();}
$("frontFileBtn").onclick=()=>$("frontInput").click();$("rakingFileBtn").onclick=()=>$("rakingInput").click();$("frontCameraBtn").onclick=()=>$("frontCameraInput").click();$("rakingCameraBtn").onclick=()=>$("rakingCameraInput").click();
$("frontInput").onchange=e=>setImage("front",e.target.files?.[0],`ファイル: ${e.target.files?.[0]?.name||""}`);$("rakingInput").onchange=e=>setImage("raking",e.target.files?.[0],`ファイル: ${e.target.files?.[0]?.name||""}`);$("frontCameraInput").onchange=e=>setImage("front",e.target.files?.[0],"カメラで撮影済み");$("rakingCameraInput").onchange=e=>setImage("raking",e.target.files?.[0],"カメラで撮影済み");
async function loadImage(src){if(!src)return null;const im=new Image();im.src=src;await im.decode();return im;}
async function prepareEditor(){const src=frontURL||rakingURL;$("roiEditorEmpty").hidden=!!src;roiCanvas.hidden=!src;if(!src){editorImage=null;return;}editorImage=await loadImage(src);drawEditor();}
function resizeEditor(){const w=Math.max(280,roiCanvas.clientWidth||320),h=Math.min(560,Math.max(360,Math.round(w*1.15))),dpr=Math.min(devicePixelRatio||1,2);roiCanvas.width=Math.round(w*dpr);roiCanvas.height=Math.round(h*dpr);roiCanvas.style.height=h+"px";rctx.setTransform(dpr,0,0,dpr,0,0);return{w,h};}
function drawEditor(){if(!editorImage)return;const{w,h}=resizeEditor();rctx.clearRect(0,0,w,h);rctx.fillStyle="#0b1020";rctx.fillRect(0,0,w,h);const s=Math.min(w/editorImage.naturalWidth,h/editorImage.naturalHeight),dw=editorImage.naturalWidth*s,dh=editorImage.naturalHeight*s,x=(w-dw)/2,y=(h-dh)/2;imageRect={x,y,w:dw,h:dh};rctx.drawImage(editorImage,x,y,dw,dh);const L=x+roi.l*dw,R=x+roi.r*dw,T=y+roi.t*dh,B=y+roi.b*dh;rctx.save();rctx.fillStyle="rgba(0,0,0,.48)";rctx.beginPath();rctx.rect(x,y,dw,dh);rctx.rect(L,T,R-L,B-T);rctx.fill("evenodd");rctx.strokeStyle=roiConfirmed?"#10b981":"#f59e0b";rctx.lineWidth=3;rctx.strokeRect(L,T,R-L,B-T);rctx.setLineDash([6,5]);rctx.lineWidth=1.5;rctx.beginPath();rctx.moveTo(L,(T+B)/2);rctx.lineTo(R,(T+B)/2);rctx.moveTo((L+R)/2,T);rctx.lineTo((L+R)/2,B);rctx.stroke();rctx.setLineDash([]);[{k:"top",x:(L+R)/2,y:T,label:"上端"},{k:"bottom",x:(L+R)/2,y:B,label:"下端"},{k:"left",x:L,y:(T+B)/2,label:"左端"},{k:"right",x:R,y:(T+B)/2,label:"右端"}].forEach(p=>{rctx.fillStyle="#fff";rctx.beginPath();rctx.arc(p.x,p.y,12,0,Math.PI*2);rctx.fill();rctx.strokeStyle=roiConfirmed?"#10b981":"#f59e0b";rctx.lineWidth=4;rctx.stroke();rctx.font="bold 12px system-ui";rctx.textAlign="center";rctx.fillStyle="#fff";const yy=p.k==="top"?p.y-18:p.k==="bottom"?p.y+28:p.y-18;rctx.fillText(p.label,p.x,yy);});rctx.restore();}
function pointerPos(e){const rect=roiCanvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};}
function nearestEdge(p){if(!imageRect)return null;const L=imageRect.x+roi.l*imageRect.w,R=imageRect.x+roi.r*imageRect.w,T=imageRect.y+roi.t*imageRect.h,B=imageRect.y+roi.b*imageRect.h;const d=[["top",Math.abs(p.y-T),p.x>=L-30&&p.x<=R+30],["bottom",Math.abs(p.y-B),p.x>=L-30&&p.x<=R+30],["left",Math.abs(p.x-L),p.y>=T-30&&p.y<=B+30],["right",Math.abs(p.x-R),p.y>=T-30&&p.y<=B+30]].filter(x=>x[2]).sort((a,b)=>a[1]-b[1]);return d[0]&&d[0][1]<32?d[0][0]:null;}
roiCanvas.addEventListener("pointerdown",e=>{dragging=nearestEdge(pointerPos(e));if(dragging){roiCanvas.setPointerCapture(e.pointerId);roiConfirmed=false;setROIStatus();}});roiCanvas.addEventListener("pointermove",e=>{if(!dragging||!imageRect)return;const p=pointerPos(e),nx=Math.min(1,Math.max(0,(p.x-imageRect.x)/imageRect.w)),ny=Math.min(1,Math.max(0,(p.y-imageRect.y)/imageRect.h)),gap=.08;if(dragging==="left")roi.l=Math.min(nx,roi.r-gap);if(dragging==="right")roi.r=Math.max(nx,roi.l+gap);if(dragging==="top")roi.t=Math.min(ny,roi.b-gap);if(dragging==="bottom")roi.b=Math.max(ny,roi.t+gap);drawEditor();});["pointerup","pointercancel"].forEach(ev=>roiCanvas.addEventListener(ev,()=>dragging=null));
$("resetRoiBtn").onclick=()=>{roi=cloneROI(currentRegion().roi);roiConfirmed=false;setROIStatus();drawEditor();};$("confirmRoiBtn").onclick=()=>{if(!(frontURL||rakingURL)){alert("先に画像を選んでください。");return;}roiConfirmed=true;setROIStatus();drawEditor();};
function setROIStatus(){const el=$("roiStatus");if(!(frontURL||rakingURL)){el.textContent="画像を入れるとROI調整ができます";el.className="note";return;}if(roiConfirmed){el.innerHTML="<b>ROI確定済み</b> — この範囲だけを解析します。";el.className="note goodNote";}else{el.innerHTML="<b>ROI未確定</b> — 4本の境界線を指で動かして、解析する皮膚だけを囲ってください。";el.className="warnBox";}}
function clearAnalysis(){const w=Math.max(320,analysisCanvas.clientWidth||320),h=Math.round(w*1.1);analysisCanvas.width=w;analysisCanvas.height=h;actx.fillStyle="#111827";actx.fillRect(0,0,w,h);}
async function analyzeCurrentRegion(){const src=rakingURL||frontURL;if(!src){alert("正面光または斜光画像を入れてください。");return;}if(!roiConfirmed){alert("先にROIを確定してください。");return;}$("analysisSource").innerHTML=rakingURL?"<b>解析に使用:</b> 斜光画像 × 確定ROI":"<b>解析に使用:</b> 正面光画像 × 確定ROI";const img=await loadImage(src),sx=Math.round(roi.l*img.naturalWidth),sy=Math.round(roi.t*img.naturalHeight),sw=Math.max(10,Math.round((roi.r-roi.l)*img.naturalWidth)),sh=Math.max(10,Math.round((roi.b-roi.t)*img.naturalHeight)),scale=Math.min(1,620/sw),w=Math.max(120,Math.round(sw*scale)),h=Math.max(120,Math.round(sh*scale));analysisCanvas.width=w;analysisCanvas.height=h;actx.drawImage(img,sx,sy,sw,sh,0,0,w,h);const image=actx.getImageData(0,0,w,h),d=image.data,gray=new Float32Array(w*h);for(let i=0,p=0;i<d.length;i+=4,p++)gray[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];const blur=boxBlur(gray,w,h,9),map=new Uint8Array(w*h);let tex=0,n=0;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,local=blur[i]-gray[i],gx=gray[i+1]-gray[i-1],gy=gray[i+w]-gray[i-w],grad=Math.hypot(gx,gy);tex+=Math.abs(local);n++;if(local>11&&grad>9)map[i]=1;}const comps=components(map,w,h);actx.drawImage(img,sx,sy,sw,sh,0,0,w,h);let area=0;comps.forEach((c,i)=>{area+=c.area;const t=classify(c);actx.strokeStyle=t.color;actx.lineWidth=1.5;actx.strokeRect(c.x,c.y,c.w,c.h);actx.fillStyle=t.color;actx.font="10px system-ui";actx.fillText(String(i+1),c.x+1,Math.max(10,c.y-2));});lastMetrics={candidates:comps.length,areaRatio:100*area/(w*h),texture:n?tex/n:0,avgSize:comps.length?area/comps.length:0,components:comps.map(classify),roi:cloneROI(roi)};fillMetrics(lastMetrics);}
function components(map,w,h){const seen=new Uint8Array(w*h),out=[],dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const s=y*w+x;if(!map[s]||seen[s])continue;const q=[s];seen[s]=1;let area=0,minX=x,maxX=x,minY=y,maxY=y;while(q.length){const cur=q.pop(),cx=cur%w,cy=(cur/w)|0;area++;minX=Math.min(minX,cx);maxX=Math.max(maxX,cx);minY=Math.min(minY,cy);maxY=Math.max(maxY,cy);for(const[dx,dy]of dirs){const nx=cx+dx,ny=cy+dy,ni=ny*w+nx;if(nx>0&&ny>0&&nx<w-1&&ny<h-1&&map[ni]&&!seen[ni]){seen[ni]=1;q.push(ni);}}}const bw=maxX-minX+1,bh=maxY-minY+1;if(area>=8&&area<=Math.max(800,Math.round(w*h*.03)))out.push({x:minX,y:minY,w:bw,h:bh,area,aspect:Math.max(bw,bh)/Math.max(1,Math.min(bw,bh))});}return out;}
function classify(c){if(c.area<35&&c.aspect<1.7)return{...c,label:"I",color:"rgba(239,68,68,.95)"};if(c.aspect<1.45&&c.area>=35)return{...c,label:"B",color:"rgba(34,197,94,.95)"};return{...c,label:"R",color:"rgba(59,130,246,.95)"};}
function boxBlur(g,w,h,r){const tmp=new Float32Array(w*h),out=new Float32Array(w*h),size=2*r+1;for(let y=0;y<h;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=g[y*w+Math.min(w-1,Math.max(0,x))];for(let x=0;x<w;x++){tmp[y*w+x]=sum/size;const rm=x-r,ad=x+r+1;if(rm>=0)sum-=g[y*w+rm];if(ad<w)sum+=g[y*w+ad];else sum+=g[y*w+w-1];}}for(let x=0;x<w;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=tmp[Math.min(h-1,Math.max(0,y))*w+x];for(let y=0;y<h;y++){out[y*w+x]=sum/size;const rm=y-r,ad=y+r+1;if(rm>=0)sum-=tmp[rm*w+x];if(ad<h)sum+=tmp[ad*w+x];else sum+=tmp[(h-1)*w+x];}}return out;}
function fillMetrics(m){$("mCandidates").textContent=m?m.candidates:"—";$("mAreaRatio").textContent=m?m.areaRatio.toFixed(2)+"%":"—";$("mTexture").textContent=m?m.texture.toFixed(2):"—";$("mAvgSize").textContent=m?m.avgSize.toFixed(1)+" px²":"—";}
$("analyzeBtn").onclick=analyzeCurrentRegion;
$("saveRegionBtn").onclick=()=>{if(!(frontURL||rakingURL)){alert("画像を入れてください。");return;}if(!roiConfirmed){alert("ROIを確定してください。");return;}const r=currentRegion();state.sessionName=$("sessionName").value;state.lightingPreset=$("lightingPreset").value;state.regions[r.key]={name:r.name,frontDataUrl:frontURL,rakingDataUrl:rakingURL,roi:cloneROI(roi),roiConfirmed:true,overlayDataUrl:analysisCanvas.toDataURL("image/png"),metrics:lastMetrics};buildWizard();renderSummary();alert(`${r.name} を保存しました。`);};
function renderSummary(){summaryTabs.innerHTML="";const keys=Object.keys(state.regions);if(!keys.length){$("summaryPane").textContent="まだ部位は保存されていません。";return;}keys.forEach((k,i)=>{const b=document.createElement("button");b.textContent=state.regions[k].name;if(i===0)b.classList.add("active");b.onclick=()=>{[...summaryTabs.children].forEach(x=>x.classList.remove("active"));b.classList.add("active");showSummary(k);};summaryTabs.appendChild(b);});showSummary(keys[0]);}
function showSummary(k){const s=state.regions[k],m=s.metrics;$("summaryPane").innerHTML=`<b>${s.name}</b><br>ROI: ${s.roi?`${Math.round(s.roi.l*100)}–${Math.round(s.roi.r*100)}% × ${Math.round(s.roi.t*100)}–${Math.round(s.roi.b*100)}%`:"—"}<br>候補数: ${m?m.candidates:"—"} / 面積率: ${m?m.areaRatio.toFixed(2)+"%":"—"}`;}
$("prevStep").onclick=()=>switchRegion((state.current-1+regions.length)%regions.length);$("nextStep").onclick=()=>switchRegion((state.current+1)%regions.length);
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="acne_scar_session_v0_6.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$("resetBtn").onclick=()=>{if(!confirm("セッション全体をリセットしますか？"))return;state.current=0;state.sessionName="";state.lightingPreset="left-raking";state.regions={};$("sessionName").value="";$("lightingPreset").value="left-raking";switchRegion(0);};
window.addEventListener("resize",()=>drawEditor());if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn);roi=cloneROI(currentRegion().roi);buildWizard();updateUI();
